---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask-deployment
  namespace: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-flask
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      containers:
      - name: hello-flask
        image: stradivirus/hello
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-flask-service
  namespace: hello
spec:
  selector:
    app: hello-flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort

